{{- if $.Values.auth.fileRealm }}
  {{- if or $.Values.auth.fileRealm.users $.Values.auth.fileRealm.users_roles -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "eck.name" $ }}-auth-realm
  labels: {{ include "eck.labels" . | nindent 4 }}
stringData:
    {{- if $.Values.auth.fileRealm.users }}
  users: |-
      {{- range $.Values.auth.fileRealm.users }}
        {{- .name | nindent 4 }}:{{ .password }} 
      {{- end }}
    {{- end -}}
    {{- if $.Values.auth.fileRealm.users_roles }}
  user_roles: |-
      {{- range .Values.auth.fileRealm.users_roles }}
        {{- .user | nindent 4 }}:{{ .role }}
      {{- end -}}
    {{- end -}}
  {{- end -}}    
{{- end }}
