{{- if $.Values.auth.roles }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "eck.name" $ }}-auth-roles
  labels: {{ include "eck.labels" . | nindent 4 }}
stringData:
  roles.yml: |- {{- toYaml $.Values.auth.roles | nindent 4 }}
{{- end }}
